default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: <%= ENV['RAILS_DATABASE_USERNAME'] || 'rails' %>
  password: <%= ENV['RAILS_DATABASE_PASSWORD'] || 'rails' %>
  host: <%= ENV['RAILS_DATABASE_HOST'] || 'localhost' %>
  port: 3306
  pool: 30
  timeout: 30000

development:
  <<: *default
  database: testapp_development
  collation: utf8_general_ci
  charset: utf8

test:
  <<: *default
  database: testapp_test
  collation: utf8_general_ci
  charset: utf8

staging:
  <<: *default
  database: testapp
  collation: utf8_general_ci
  charset: utf8

production:
  <<: *default
  database: testapp
  collation: utf8_general_ci
  charset: utf8
